# Generated by Django 4.2 on 2024-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("open", models.CharField(max_length=100)),
                ("high", models.CharField(max_length=100)),
                ("low", models.CharField(max_length=100)),
                ("close", models.CharField(max_length=100)),
                ("volume", models.CharField(max_length=100)),
            ],
        ),
    ]
